apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "coredevs.fullname" . }}-data
  labels:
    {{- include "coredevs.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- with .Values.storage.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
